#!/usr/bin/env python3
"""Generate src/renderer/bidi_table.zig from the Unicode Character Database.

    python3 tools/gen_bidi_table.py DerivedBidiClass.txt BidiBrackets.txt > src/renderer/bidi_table.zig
    zig fmt src/renderer/bidi_table.zig

The `zig fmt` pass is not optional: it column-aligns the table rows this script emits
single-spaced, and the committed file is formatted. Skipping it re-diffs all 380 lines.

Both inputs come from https://www.unicode.org/Public/UCD/latest/ucd/
(DerivedBidiClass.txt lives under extracted/). Regenerate on a Unicode upgrade;
nothing in the build depends on this script.
"""

import re
import sys

CLASSES = [
    "L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN",
    "B", "S", "WS", "ON",
    "LRE", "RLE", "LRO", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI",
]
LONG = {
    "Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL",
    "European_Number": "EN", "European_Separator": "ES", "European_Terminator": "ET",
    "Arabic_Number": "AN", "Common_Separator": "CS", "Nonspacing_Mark": "NSM",
    "Boundary_Neutral": "BN", "Paragraph_Separator": "B", "Segment_Separator": "S",
    "White_Space": "WS", "Other_Neutral": "ON",
}
MAX = 0x110000


def load_classes(path):
    """Full Bidi_Class map, @missing defaults first so real assignments win."""
    cls = ["L"] * MAX
    missing = re.compile(r"#\s*@missing:\s*([0-9A-F]{4,6})\.\.([0-9A-F]{4,6})\s*;\s*(\w+)")
    entry = re.compile(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*(\w+)")
    lines = open(path, encoding="utf-8").read().splitlines()
    for line in lines:  # pass 1: defaults for unassigned code points
        m = missing.search(line)
        if m:
            lo, hi, name = int(m[1], 16), int(m[2], 16), LONG[m[3]]
            for cp in range(lo, min(hi + 1, MAX)):
                cls[cp] = name
    for line in lines:  # pass 2: assigned code points
        line = line.split("#")[0]
        m = entry.match(line)
        if m:
            lo = int(m[1], 16)
            hi = int(m[2], 16) if m[2] else lo
            for cp in range(lo, min(hi + 1, MAX)):
                cls[cp] = m[3]
    return cls


def load_brackets(path):
    """(open, close) pairs from Bidi_Paired_Bracket_Type=Open entries."""
    pairs = []
    for line in open(path, encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue
        cp, paired, kind = (f.strip() for f in line.split(";"))
        if kind == "o":
            pairs.append((int(cp, 16), int(paired, 16)))
    return sorted(pairs)


def main():
    cls = load_classes(sys.argv[1])
    pairs = load_brackets(sys.argv[2])

    # Boundaries only: a code point's class is the one at the greatest start <= cp.
    starts, values = [0], [cls[0]]
    for cp in range(1, MAX):
        if cls[cp] != values[-1]:
            starts.append(cp)
            values.append(cls[cp])

    out = sys.stdout.write
    out("//! Generated by tools/gen_bidi_table.py from the Unicode Character Database.\n")
    out("//! Bidi_Class ranges (UAX #9 / UAX #44) and Bidi_Paired_Bracket pairs. Do not edit.\n\n")
    out("const std = @import(\"std\");\n\n")
    out("/// UAX #9 Bidi_Class, in the order the standard lists them: strong, weak, neutral,\n")
    out("/// then the explicit formatting classes.\n")
    out("pub const Class = enum(u8) {\n")
    for name in CLASSES:
        out(f"    {name.lower()},\n")
    out("};\n\n")

    out(f"/// Start of each Bidi_Class range ({len(starts)} boundaries covering U+0000..U+10FFFF).\n")
    out("const starts = [_]u21{\n")
    for i in range(0, len(starts), 8):
        out("    " + " ".join(f"0x{s:X}," for s in starts[i:i + 8]) + "\n")
    out("};\n\n")
    out("/// Class of the range beginning at the matching entry of `starts`.\n")
    out("const classes = [_]Class{\n")
    for i in range(0, len(values), 10):
        out("    " + " ".join(f".{v.lower()}," for v in values[i:i + 10]) + "\n")
    out("};\n\n")
    out("/// Bidi_Class of `cp`, including the R/AL/ET/BN defaults for unassigned code points.\n")
    out("pub fn classOf(cp: u21) Class {\n")
    out("    const i = std.sort.upperBound(u21, &starts, cp, struct {\n")
    out("        fn order(key: u21, mid: u21) std.math.Order {\n")
    out("            return std.math.order(key, mid);\n")
    out("        }\n")
    out("    }.order);\n")
    out("    return classes[i - 1];\n")
    out("}\n\n")

    out(f"/// Bidi_Paired_Bracket: opening code point → its closing partner ({len(pairs)} pairs).\n")
    out("const bracket_open = [_]u21{\n")
    for i in range(0, len(pairs), 8):
        out("    " + " ".join(f"0x{o:X}," for o, _ in pairs[i:i + 8]) + "\n")
    out("};\n")
    out("const bracket_close = [_]u21{\n")
    for i in range(0, len(pairs), 8):
        out("    " + " ".join(f"0x{c:X}," for _, c in pairs[i:i + 8]) + "\n")
    out("};\n\n")
    out("/// The closing bracket paired with `cp`, or null when `cp` opens nothing.\n")
    out("/// Canonical equivalents are folded (BD16 note): U+2329/U+232A behave as U+3008/U+3009.\n")
    out("pub fn pairedBracket(cp: u21) ?u21 {\n")
    out("    const key = canonicalBracket(cp);\n")
    out("    const i = std.sort.binarySearch(u21, &bracket_open, key, struct {\n")
    out("        fn order(k: u21, mid: u21) std.math.Order {\n")
    out("            return std.math.order(k, mid);\n")
    out("        }\n")
    out("    }.order) orelse return null;\n")
    out("    return bracket_close[i];\n")
    out("}\n\n")
    out("/// Fold the two brackets with a canonical decomposition onto their equivalents, so a\n")
    out("/// U+2329 open matches a U+3009 close and vice versa.\n")
    out("pub fn canonicalBracket(cp: u21) u21 {\n")
    out("    return switch (cp) {\n")
    out("        0x2329 => 0x3008,\n")
    out("        0x232A => 0x3009,\n")
    out("        else => cp,\n")
    out("    };\n")
    out("}\n")


if __name__ == "__main__":
    main()
